language: node_js
dist: trusty
addons:
  chrome: stable
node_js:
- node
env:
  - NODE_ENV=production
before_install:
  - google-chrome-stable --headless --no-sandbox --remote-debugging-port=9222 &
install:
- npm --production=false install
- npm --production=false update
sudo: false
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script:
      - npm run lint
      - npm run docs
      - npm run tap
    - stage: deploy
      node_js: node
      script: npm run build
      if: branch = release
      before_deploy:
      - VPKG=$("$(npm bin)/json" -f package.json version)
      - export VERSION=${VPKG}-prerelease.$(date +%Y-%m-%dT%H-%MZ --utc)
      - npm --no-git-tag-version version $VERSION
      - git config --global user.email "$(git log --pretty=format:'%ae' -n1)"
      - git config --global user.name "$(git log --pretty=format:'%an' -n1)"
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: release